version: "3.9"

services:
  backend:
    build: .
    ports:
      - 8000:8000
    container_name: banking-app
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_USER: johnwick
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 33066:3306

volumes:
  mysqldata:
    driver: local
