version: "3.9"

services:
  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  mysqldata:
    driver: local
